# Create, Save, and Explore a Student DataFrame Using Pandas

This project demonstrates how to create a student DataFrame using Pandas, save it as a CSV file, reload the data, and explore the DataFrame.

In [1]:
import pandas as pd

## Step 2: Create the Student DataFrame

We create a dictionary containing student information and convert it into a Pandas DataFrame.

In [3]:
data = {
    "StudentID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Ethan",
             "Fiona", "George", "Hannah", "Ivan", "Julia"],
    "Age": [20, 21, 19, 22, 20, 21, 23, 19, 22, 20],
    "Marks": [88, 75, 92, 65, 78, 85, 70, 95, 60, 80],
    "Grade": ["A", "B", "A", "C", "B", "A", "B", "A", "C", "B"]
}

df = pd.DataFrame(data)

df

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

## Step 3: Save the DataFrame as a CSV File

We save the DataFrame as `students.csv` so that the data can be stored and used later.

In [4]:
df.to_csv("students.csv", index=False)

print("students.csv file saved successfully.")

students.csv file saved successfully.

## Step 4: Reload the CSV File

We read the saved `students.csv` file using Pandas and store it again in a DataFrame.

In [5]:
df = pd.read_csv("students.csv")

df

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A
3        104    Diana   22     65     C
4        105    Ethan   20     78     B
5        106    Fiona   21     85     A
6        107   George   23     70     B
7        108   Hannah   19     95     A
8        109     Ivan   22     60     C
9        110    Julia   20     80     B

## Step 5: Display the First 3 Rows

The `head(3)` method displays the first three rows of the DataFrame.

In [6]:
df.head(3)

   StudentID     Name  Age  Marks Grade
0        101    Alice   20     88     A
1        102      Bob   21     75     B
2        103  Charlie   19     92     A

## Step 6: Statistical Summary

The `describe()` method provides statistical information about the numerical columns in the DataFrame, such as count, mean, standard deviation, minimum, and maximum.

In [7]:
df.describe()

       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean   105.50000  20.700000  78.800000
std      3.02765   1.337494  11.535453
min    101.00000  19.000000  60.000000
25%    103.25000  20.000000  71.250000
50%    105.50000  20.500000  79.000000
75%    107.75000  21.750000  87.250000
max    110.00000  23.000000  95.000000

## Step 7: Check the Shape of the DataFrame

The `shape` attribute tells us the number of rows and columns in the DataFrame.

In [8]:
df.shape

(10, 5)

## Step 8: Check Data Types

The `dtypes` attribute shows the data type of each column in the DataFrame.

In [9]:
df.dtypes

StudentID     int64
Name         object
Age           int64
Marks         int64
Grade        object
dtype: object

## Step 9: Display DataFrame Information

The `info()` method gives an overview of the DataFrame, including the number of rows, columns, non-null values, and data types.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  10 non-null     int64
 1   Name       10 non-null     object
 2   Age        10 non-null     int64
 3   Marks      10 non-null     int64
 4   Grade      10 non-null     object
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

## Conclusion

In this project, we learned how to:

- Import the Pandas library.
- Create a DataFrame using a Python dictionary.
- Save the DataFrame as a CSV file.
- Reload data from a CSV file.
- Display the first 3 rows using `head(3)`.
- Generate a statistical summary using `describe()`.
- Check the number of rows and columns using `shape`.
- Check column data types using `dtypes`.
- Understand the structure of the DataFrame using `info()`.

### What We Learned

Pandas makes it easy to create, store, and explore tabular data in Python. These basic operations are important for data analysis and are commonly used in real-world data projects.